spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
    show-sql: true
  flyway:
    enabled: true
    locations: filesystem:src/main/resources/db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/database?user=user&password=password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 3
      idle-timeout: 100
      connection-timeout: 10000
      max-lifetime: 120000
  security:
    oauth2:
      client:
        registration:
          github:
            base-url: https://github.com
            client-id: ${GITHUB_CLIENT_ID:your-id-here}
            client-secret: ${GITHUB_CLIENT_SECRET:your-secret-here}
            scope: read:user
            #            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-authentication-method: post
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
server:
  error:
    include-stacktrace: on-param
    include-exception: false
    include-binding-errors: always
    include-message: always
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
      expiration: ${JWT_EXPIRATION:604800}
      issuer: ${JWT_ISSUER:issuer}